- name: Preparing Ubuntu 22 WSL2 Workstation
  hosts: localhost
  connection: local
  tasks:
    - name: Checking OS
      debug: msg={{ansible_distribution}}-{{ansible_distribution_version}}     
  roles:
    - role: essentials
    - role: ufw
    - role: zsh
    - role: cargo
    - role: aws
    - role: terraform
    - role: tools
  tags: [ubuntu22, never] 
