  - name: Download Rust Installer
    get_url:
      url: https://sh.rustup.rs
      dest: /tmp/sh.rustup.rs
      mode: '0755'
      force: 'yes'
    tags:
      - rust

  - name: install rust/cargo
    shell: /tmp/sh.rustup.rs -y
    tags:
      - rust

  - name: Insert cargo source dir in .zshrc
    lineinfile:
      path: $HOME/.zshrc
      regexp: '# ~/.zshrc'
      insertafter: ^# export ZSH="$HOME/.oh-my-zsh"
      line: 'source $HOME/.cargo/env'

