---
- name: Preparing Workstation
  hosts: localhost
  connection: local
  tasks:

    - name: Installing Base Apps for Developer
      become: true
      apt:
        name: '{{ item }}'
        install_recommends: yes
        state: present
      loop:
        - build-essential
        - default-jdk
        - libssl-dev
        - exuberant-ctags
        - ncurses-term
        - ack-grep
        - silversearcher-ag
        - fontconfig
        - imagemagick
        - libmagickwand-dev
        - software-properties-common
        - vim-gtk3
        - curl
        - xterm
        - openjfx
        - maven
        - nmap
        - net-tools
        - traceroute
        - git
        - g++
        - cmake
        - libjsoncpp-dev
        - uuid-dev
        - openssl
        - zlib1g-dev
        - rlwrap
        - gawk
        - sqlite
        - libsqlite3-dev
        - m4
        - libncurses5-dev
        - libwxgtk3.0-gtk3-dev
        - libwxgtk-webview3.0-gtk3-dev
        - libgl1-mesa-dev
        - libglu1-mesa-dev
        - libpng-dev
        - libssh-dev
        - unixodbc-dev
        - xsltproc
        - fop
        - libxml2-utils
        - libncurses-dev
        - openjdk-11-jdk
        - automake
        - autoconf
        - libreadline-dev
        - libyaml-dev
        - libxslt-dev
        - libffi-dev
        - libtool
        - unzip
        - sqlite3
        - libsqlite3-dev
        - gcc
        - zsh
        - neofetch
        - sassc
        - sqlite
        - libsqlite3-dev
        - ubuntu-restricted-extras
        - gnupg
        - ca-certificates
        - python3-dev
        - python3-pip
        - python3-apt
        - pwgen
        - nodejs
        - npm
        - yarn
        - apache2
        - php
        - libapache2-mod-php
        - php-soap
        - php-xml
        - php-curl
        - php-opcache
        - php-gd
        - php-sqlite3
        - php-mbstring
        - neovim        
        - fonts-hack            
        - redis-server
        - libhiredis-dev
        - memcached
        - libmemcached-dev                 
        - php-mysql
        - jq
        - mtr        
        - htop
        - wget
        - ncdu
        - tree
        - apt-transport-https
        - make
        - bash-completion
        - gnupg-agent
        - mlocate
        - gnome-themes-extra
        - gtk2-engines-murrine
        - emacs
      ignore_errors: true

    - name: Installing Gstreamer for Wsl2
      become: true
      apt:
        name: '{{ item }}'
        install_recommends: yes
        state: present
      loop:
        - libgstreamer1.0-dev
        - libgstreamer-plugins-base1.0-dev
        - libgstreamer-plugins-bad1.0-dev
        - gstreamer1.0-plugins-base
        - gstreamer1.0-plugins-good
        - gstreamer1.0-plugins-bad
        - gstreamer1.0-plugins-ugly
        - gstreamer1.0-libav
        - gstreamer1.0-tools
        - gstreamer1.0-x
        - gstreamer1.0-alsa
        - gstreamer1.0-gl
        - gstreamer1.0-gtk3
        - gstreamer1.0-qt5
        - gstreamer1.0-pulseaudio  
      ignore_errors: true
                                                                              
    - name: Installing AWS CLI via pip3
      become: true
      pip:
        name: awscli
        executable: pip3

    - block:
      - name: Installing Terraform 0.12.31
        become: true
        unarchive:
          src: 'https://releases.hashicorp.com/terraform/0.12.31/terraform_0.12.31_linux_amd64.zip'
          dest: /usr/local/bin
          remote_src: yes
      - name: Renaming terraform12 binary
        become: true
        command: mv /usr/local/bin/terraform /usr/local/bin/terraform12
      - name: Installing Terraform 0.13.7 
        become: true
        unarchive:
          src: 'https://releases.hashicorp.com/terraform/0.13.7/terraform_0.13.7_linux_amd64.zip'
          dest: /usr/local/bin
          remote_src: yes
      - name: Renaming terraform13 binary
        become: true
        command: mv /usr/local/bin/terraform /usr/local/bin/terraform13
      - name: Installing Terraform 0.14.11
        become: true
        unarchive:
          src: 'https://releases.hashicorp.com/terraform/0.14.11/terraform_0.14.11_linux_amd64.zip'
          dest: /usr/local/bin
          remote_src: yes
      - name: Renaming terraform14 binary
        become: true
        command: mv /usr/local/bin/terraform /usr/local/bin/terraform14
      - name: Installing Terraform 0.15.0
        become: true
        unarchive:
          src: 'https://releases.hashicorp.com/terraform/0.15.5/terraform_0.15.5_linux_amd64.zip'
          dest: /usr/local/bin
          remote_src: yes
      - name: Renaming terraform15 binary
        become: true
        command: mv /usr/local/bin/terraform /usr/local/bin/terraform15
      - name: Installing Terraform 1.0.4
        become: true
        unarchive:
          src: 'https://releases.hashicorp.com/terraform/1.0.4/terraform_1.0.4_linux_amd64.zip'
          dest: /usr/local/bin
          remote_src: yes
      - name: Renaming terraform1 binary
        become: true
        command: mv /usr/local/bin/terraform /usr/local/bin/terraform1

    - block:
      - name: Installing Vault 1.8.1
        become: true
        unarchive:
          src: 'https://releases.hashicorp.com/vault/1.8.1/vault_1.8.1_linux_amd64.zip'
          dest: /usr/local/bin
          remote_src: yes

    - block:
      - name: Installing gomplate 3.9.0
        become: true
        get_url:    
          url: 'https://github.com/hairyhenderson/gomplate/releases/download/v3.9.0/gomplate_linux-amd64'
          dest: /usr/local/bin/gomplate
          mode: 755

    - block:
      - name: Installing Stern 1.11.0
        become: true
        get_url:    
          url: 'https://github.com/wercker/stern/releases/download/1.11.0/stern_linux_amd64'
          dest: /usr/local/bin/stern
          mode: 755
